/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RRoomIdRouteImport } from './routes/r.$roomId'
import { Route as ApiPublicPlacePhotoSplatRouteImport } from './routes/api/public/place-photo.$'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RRoomIdRoute = RRoomIdRouteImport.update({
  id: '/r/$roomId',
  path: '/r/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPlacePhotoSplatRoute =
  ApiPublicPlacePhotoSplatRouteImport.update({
    id: '/api/public/place-photo/$',
    path: '/api/public/place-photo/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/r/$roomId': typeof RRoomIdRoute
  '/api/public/place-photo/$': typeof ApiPublicPlacePhotoSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/r/$roomId': typeof RRoomIdRoute
  '/api/public/place-photo/$': typeof ApiPublicPlacePhotoSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/r/$roomId': typeof RRoomIdRoute
  '/api/public/place-photo/$': typeof ApiPublicPlacePhotoSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sitemap.xml' | '/r/$roomId' | '/api/public/place-photo/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sitemap.xml' | '/r/$roomId' | '/api/public/place-photo/$'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/r/$roomId'
    | '/api/public/place-photo/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  RRoomIdRoute: typeof RRoomIdRoute
  ApiPublicPlacePhotoSplatRoute: typeof ApiPublicPlacePhotoSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$roomId': {
      id: '/r/$roomId'
      path: '/r/$roomId'
      fullPath: '/r/$roomId'
      preLoaderRoute: typeof RRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/place-photo/$': {
      id: '/api/public/place-photo/$'
      path: '/api/public/place-photo/$'
      fullPath: '/api/public/place-photo/$'
      preLoaderRoute: typeof ApiPublicPlacePhotoSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  RRoomIdRoute: RRoomIdRoute,
  ApiPublicPlacePhotoSplatRoute: ApiPublicPlacePhotoSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
